version: 2.1
orbs:
	node: circleci/node@3.0.0
workflows:
	node-tests:
 jobs:
	- node/test
    steps:
      - checkout # check out the code in the project directory
      - run: npm install 
      - run: npm start & 
      - run: npm test 

  